import Foundation

public enum ContentKind: String, Codable, CaseIterable { case text, link, image, audio, document }

public struct ClipboardItem: Identifiable, Equatable {
    public let id: Int64
    public let kind: ContentKind
    public let text: String?
    public let copiedAt: Date
    public let source: String?
    public let filename: String?
    public let pinned: Bool
    public let fingerprint: String
    public func matches(_ query: String) -> Bool {
        query.isEmpty || (text?.range(of: query, options: [.caseInsensitive, .diacriticInsensitive]) != nil)
    }
    public init(id: Int64, kind: ContentKind, text: String?, copiedAt: Date, source: String?, filename: String? = nil,
                pinned: Bool, fingerprint: String) {
        self.id = id; self.kind = kind; self.text = text; self.copiedAt = copiedAt
        self.source = source; self.filename = filename; self.pinned = pinned; self.fingerprint = fingerprint
    }
}

public enum PrivacyPolicy {
    public static let sensitiveTypes: Set<String> = [
        "org.nspasteboard.TransientType", "org.nspasteboard.ConcealedType",
        "org.nspasteboard.AutoGeneratedType", "de.petermaurer.TransientPasteboardType",
        "com.typeit4me.clipping", "Pasteboard generator type", "com.agilebits.onepassword"
    ]
    public static let defaultIgnoredApps: Set<String> = [
        "com.1password.1password", "com.agilebits.onepassword7", "com.agilebits.onepassword-osx",
        "com.bitwarden.desktop", "com.dashlane.Dashlane", "com.enpass.Enpass", "com.apple.Passwords"
    ]
    public static func shouldCapture(types: Set<String>, sources: [String], ignoredApps: Set<String>) -> Bool {
        types.isDisjoint(with: sensitiveTypes) && sources.allSatisfy { !ignoredApps.contains($0) }
    }
}
